### ISSUE TITLE
Release multiple variants of the app to support multiple users

### ISSUE THREAD

**Issue by ireneusz-ptak** [pachi81/GlucoDataAuto#11]
Still waiting for my Android Auto car, but it seems the app is what I need.

The only problem is that I'd like to display data from two separate users - I already have two separate xDrip variants on my phone so all that is missing are the variants of your app - could you release something like that?

With xDrip one app would send the data to de.michelinside.glucodataauto, the other one to de.michelinside.glucodataauto2 (or similar). Is it doable?

Also it would be great to tell the apps variants apart (with name, color - doesn't matter) so I know which bg is which :)

**Comment by pachi81** [comment]
Hi,
Are you using Spotify or any other Media Player?
Not sure, if it is really useable as you can have only one notification at same time in Android Auto.
The only solution is to use fake Media Player and Notification. 
But do you really need to see the data of both in the car?

**Comment by ireneusz-ptak** [comment]
Yep, I'll probably use Spotify.

Didn't know about the limitations - using both methods might not be the best solution.
Having both BGs at the same screen would be great when you're travelling with the kids - looking at phone screen while driving is probably not the best idea. Getting the alerts would be probably easier, but still it would be good know whose BG is that.

**Comment by pachi81** [comment]
I have to think about. Maybe just try it out for one source, first, so you will see the limitations.
Do you have a phone with AOD? Maybe use the the AOD for one and Android Auto for the other child.
If I have some time, I will play around, but the Christmas time is a very busy time...

**Comment by pachi81** [comment]
So, it is possible to create a second instance of GDA.
I will add an optional string for popup, so you can fill in the name of your child, so you will know, which value is shown.
Do you already have Android Auto?

**Comment by ireneusz-ptak** [comment]
Not yet, should have it in a week.

**Comment by pachi81** [comment]
Ok! No, problem. It seems to work with two variants:
![Screenshot 2024-12-16 200324](https://github.com/user-attachments/assets/03cf3cb9-d565-45b0-b149-daa4ee1a5501)



![Screenshot 2024-12-16 200414](https://github.com/user-attachments/assets/f75f258b-4cbc-4d2b-88a0-65d70708ce89)

**Comment by ireneusz-ptak** [comment]
Cool, should do the trick :)

**Comment by ireneusz-ptak** [comment]
@pachi81 Where can I get the latest releases (both) from?

**Comment by pachi81** [comment]
Here:
https://drive.google.com/drive/folders/1SFBdrZBXvgZwPBfHaiCpssyuxZOXZwRk

**Comment by ireneusz-ptak** [comment]
Thanks, works great!

**Comment by pachi81** [comment]
Thank you for the feedback!
One more question, does it make sense to add the name also to the media player?

**Comment by ireneusz-ptak** [comment]
It won't be as important as for notifications (as there could be only one), but I think it might be useful for someone.
