### ISSUE TITLE
Dummy player modification

### ISSUE THREAD

**Issue by dufi2profor** [pachi81/GlucoDataAuto#3]
Hello, it is not an issue, i could not make new pull request.
It is more like feature request:
would it be possible to change the mode of the number with arrow to only arrow in the area? 
The glucose value with time is already there and it is not neccessary to have alternate number there especially if there is little GlucoDataAuto icon there, so the number is not visible completely:)

Just an idea. To have only arrow.
Thank You

**Comment by pachi81** [comment]
Hi, yes I can provide a setting to change it.

**Comment by dufi2profor** [comment]
Hello,
brilliant!

**Comment by pachi81** [comment]
Just one question, do you mean only the small media widget in the icon bar or also the big fan art like in this picture:
https://raw.githubusercontent.com/pachi81/GlucoDataAuto/main/images/AA_media.png

**Comment by dufi2profor** [comment]
The lower one is okay for me, i mean maybe the big one would be okay to modify too.
I dont use the bog one. Just the one at the bottom
![20240301_210040](https://github.com/pachi81/GlucoDataAuto/assets/5337511/f987742d-36b8-4a9c-8f6b-af2e3cfb98d2)

**Comment by pachi81** [comment]
You are right, this should be the same as for the notification. I will check, if I can change it independent from the big one.

**Comment by pachi81** [comment]
@dufi2profor I have added a setting for changing the icon style:
https://onedrive.live.com/?authkey=%21AG8eUfvdnCAQ1G4&id=F01898105C58ADFA%211299367&cid=F01898105C58ADFA
Can you test this version 0.9.9.6.
Thank you!
Regards, Michael

**Comment by dufi2profor** [comment]
I have installed both :)
I will test it today. I have already set the three colors:)

**Comment by dufi2profor** [comment]
Another angle

![Uploading 20240306_194355.jpg…]()

**Comment by pachi81** [comment]
Great! Thank you for testing and the feedback!
Looks much better, then before! 👍

**Comment by dufi2profor** [comment]
Great and fast work, perfect.
I don't know if it does for You as well, but if i rotate phone, the widget down on the AA screen "refreshes" :D

**Comment by dufi2profor** [comment]
![20240306_194618](https://github.com/pachi81/GlucoDataAuto/assets/5337511/ea28b06c-e74c-4e27-b3b1-a468e5a6803e)

**Comment by dufi2profor** [comment]
By the way, is there a way to take screenshot of the screen on headunit? Just curious.

**Comment by dufi2profor** [comment]
And just my opinion: it is not necessary to have three colors, i mean, i see the values and i know, when it is bad, don't You think? :) but i understand somebody needs such colorful guidance :)

**Comment by dufi2profor** [comment]
Other thing, probably might not be possible, i dont know, the right media player, perhaps it would be better to have the arrow a bit higher. Now it seems centered in that whole window making it visible under the numbers. But not such issue:)

**Comment by dufi2profor** [comment]
All right, all good:)

**Comment by pachi81** [comment]
Fixed with release 0.9.10

**Comment by dufi2profor** [comment]
Hello pachi81,
i did not tried to update the app, still using the release You provided, but almost all time it happens, when i come to the car, that it  does not start with AA connected. mean the app. then i have to stop AA on my headunit and after connecting back, the glucodataaout is there fine.
Weird, any hint what i could look at?

**Comment by dufi2profor** [comment]
I found that it can work with spotify being in the launcher jut to put Gluko app on top of the list, but if it does not start, spotify takes over:) unfortunately:)

**Comment by dufi2profor** [comment]
And one personal question as You are the only person i know who does any android programming: i would like to make small device that will sit on my charging cable and would turn off the charging power when the battery reaches let say 80%.
Would it be possible for You to make an app, that will run in background and watch the percentage of battery and will report it to bluetooth device i will make. For me it is not problem to do Arduino programming with bluetooth even low energy...
I dont know, what it takes to do such thing on android, perhaps if You will be so kind and share the source for me after You do the app...i dont know.

Why i want to do it: i read an article, that to extend LiIon batery life, it is crucial not to charge it to 100 % but just to 80% so that is my at least tiny effort:)
thank YOu

**Comment by pachi81** [comment]
> And one personal question as You are the only person i know who does any android programming: i would like to make small device that will sit on my charging cable and would turn off the charging power when the battery reaches let say 80%. Would it be possible for You to make an app, that will run in background and watch the percentage of battery and will report it to bluetooth device i will make. For me it is not problem to do Arduino programming with bluetooth even low energy... I dont know, what it takes to do such thing on android, perhaps if You will be so kind and share the source for me after You do the app...i dont know.
> 
> Why i want to do it: i read an article, that to extend LiIon batery life, it is crucial not to charge it to 100 % but just to 80% so that is my at least tiny effort:) thank YOu

Sorry, I only have shorten time and in this time I will develop for GlucoDataHandler and GlucoDataAuto. So at the moment, no chance...
But I think there several Battery-Apps which will notify you, when the phone reaches 80%. Maybe you can use them. 
Or you can use Tasker for doing such stuff.

Regards, Michael

**Comment by pachi81** [comment]
> I found that it can work with spotify being in the launcher jut to put Gluko app on top of the list, but if it does not start, spotify takes over:) unfortunately:)

Therefore I need to play a real media. Maybe I will add some...
